export default {
  ADD_NOTICE: "addNotice",
  GET_NOTICE_LIST: "getNoticeList",
  GET_NOTICE: "getNotice",
  SEARCH_NOTICE: "searchNotice",
  DELETE_NOTICE: "deleteNotice",
  MODIFY_NOTICE: "modifyNotice",
  SELECT_THREE: "selectThree",

  ADD_QNA: "addQna",
  ADD_QNA_ANSWER: "addQnaAnswer",
  GET_QNA_LIST: "getQnaList",
  GET_MY_QNA_LIST: "getMyQnaList",
  GET_QNA: "getQna",
  SEARCH_QNA: "searchQna",
  DELETE_QNA: "deleteQna",
  MODIFY_QNA: "modifyQna",
  SEARCH_UNCHECKED: "searchQna",
  CHECK_QNA: "checkQna",

  USER_LOGIN: "userLogin",
  USER_LOGIN_NAVER: "userLoginNaver",
  USER_LOGIN_GOOGLE: "userLoginGoogle",
  USER_LOGOUT: "userLogout",
  CHECK_USER_INFO: "checkUserInfo",
  CHECK_TOKEN: "checkToken",
  TOKEN_REGENERATION: "tokenRegeneration",
  SET_IS_LOGIN: "setIsLogin",
  SET_IS_LOGIN_ERROR: "setIsLoginError",
  SET_IS_VALID_TOKEN: "setIsValidToken",
  CHANGE_USER_PASS: "changeUserPass",

  SEND_EMAIL_VALID: "sendEmailValid",

  GET_USER_INFO: "getUserInfo",
  SET_USER_INFO: "setUserInfo",

  SET_USER_FAVORITES: "setUserFavorites",
  GET_USER_FAVORITES: "getUserFavorites",
  ADD_USER_FAVORITE: "addUserFavorite",
  DELETE_USER_FAVORITE: "deleteUserFavorite",

  SET_SHOW_MODAL: "setShowModal",
  SET_MODAL_MESSAGE: "setModalMessage",

  GET_APT: "getApt",
  SET_APT: "setApt",
  GET_SIDO_LIST: "getSidoList",
  GET_GUGUN_LIST: "getGugunList",
  GET_EUPMYEONDONG_LIST: "getEupmyeondongList",
  SEARCH_APT: "searchApt",
  GET_APT_POLY: "getAptPoly",
  RESET_LAT_LNG_LIST: "resetLatLngList",
  GET_LAT_LNG_LIST: "getLatLngList",
  GET_LAT_LNG: "getLatLng",
  SET_ADDRESS: "setAddress",
  SET_POLY_ADDRESS: "setPolyAddress",
  SET_LOADING: "setLoading",
  MAKE_POLY: "makePoly",
  SEARCH_APT_BY_NAME: "searchAptByName",
  FIND_NAMES: "findNames",
  PUSH_TEMP: "pushTemp",
  SET_LAT_LNG_LIST: "setLatLngList",
  SET_LAT_LNG: "setLatLng",
  SET_INFO: "setInfo",
  COUNT_UP: "countUp",
  SEARCH_BY_COUNT: "searchByCount",
  SET_INDEX: "setIndex",

  SET_SHOW_FILTER: "setShowFilter",
  GET_APT_ADDRESS_FILTER: "getAptAddressFilter",
  GET_APT_NAME_FILTER: "getAptNameFilter",
  SET_APT_FILTER: "setAptFilter",
  RESET_FILTER_CONTENT: "resetFilterContent",

  GET_APT_FILTER_SEARCH: "getAptFilterSearch",

  GET_BLOG_LIST: "getBlogList",
  GET_NEWS_LIST: "getNewsList",
};
